from enum import Enum


class WorkerState(str, Enum):
    STARTING = "STARTING"
    LOADING_CONFIG = "LOADING_CONFIG"
    CONNECTING = "CONNECTING"
    REGISTERING = "REGISTERING"
    ONLINE = "ONLINE"
    HEARTBEAT = "HEARTBEAT"
    POLL_JOB = "POLL_JOB"
    NO_JOB = "NO_JOB"
    HAS_JOB = "HAS_JOB"
    EXECUTING = "EXECUTING"
    REPORT_PROGRESS = "REPORT_PROGRESS"
    REPORT_RESULT = "REPORT_RESULT"
    NETWORK_FAILURE = "NETWORK_FAILURE"
    RETRY = "RETRY"
    SHUTDOWN = "SHUTDOWN"
    STOPPING = "STOPPING"
    EXIT = "EXIT"
